### PR TITLE
Footsteps ghost

### PR DESCRIPTION
**Pull request by Misukun**

### CODE REVIEW

**Comment by Mythra** [comment]
Hey,

Thank you so much for taking the time to add stuff in while everything besides the voice lines is starting to go out of date while I work on my auto-changelog generator (which is almost done but you know -- time) 😅 !!! It's incredibly helpful.

I'm gonna do a quick:

  1. Confirmation this info, and it's times are correct (I don't know where this info has started, but I never trust something unless I see it myself in code -- there's a ton of misinformation out there).
  2. Grab you the method names/line numbers so we can add a comment.
  3. We'll probably also wanna move this to the `Ghost Powers` section, rather than adding a dedicated footstep category.

Thank you again! Be back in a flash.

**Review by Mythra — CHANGES_REQUESTED** [review]
Okay phew! Sorry I had some work related things eat my attention more than I expected.

So as mentioned in my previous comment:

  1. Let's move the spirit information to the "Ghost Powers" section, since this is a unique power to the spirit.
  2. I've checked and the "15 to 45" seconds counter is off, it's actually 15 to 40. Let's get that info updated. (The spirit 2 to 15 is correct).
  3. Let's make sure we call out the ghosts that are floating, and can't make footsteps in normal circumstances, that's the wraith.
  4. Lets also call out that all ghosts make footsteps while hunting regardless of their float-y status.

Again thank you so much for your contribution! If you don't wanna make these changes by the way just lemme know and I can close this PR, and make the changes, but I don't wanna step on your toes :)

**Comment by Misukun** [comment]
Hello good Morning.

Sorry for taking so long to answer.

I will make the relevant changes in the PR.

Another issue I wanted to comment on is that I don't have access to the game's source code. This information I have obtained after a long time of testing.

Could you be so kind to explain to me how to see the source code of the game or pass me a url of any repository where it is?

Thanks and regards :)

**Comment by Misukun** [comment]
Hello again: D

I have also added the latest changes from the last patch with the new demon hunting bonus, the new Ghost power of the yurei and a new mechanic of the mare.

All of this information can be found in the official discord patch notes for Phasmophobia.

https://discord.com/channels/435431947963990026/661365069006897154/867389020644048958

**Comment by Mythra** [comment]
Hey,

Unfortunately inspecting the game source code is a bit of a legal gray area 😅 so I can't just share it. I will say there are tutorials online for how to dumb a Unity Game compiled with IL2CPP , and inspect a native binary. You'll still have to deal with the obfuscation, but that's not a step with a tutorial or anything.

Can I ask you to remove the changelog additions? 😅 the changelog has lied before (though it's not as bad as the wiki). The game internals are usually close to what the changelog but very subtly different. We can remove those here, open up another PR for just those and I can double check them there. Other than that the footstep changes look fine to me 😄 (and keep your name in there 😄 )

**Comment by Misukun** [comment]
Hello

Ok, I understand what you tell me about the game code, however I am interested in seeing those tutorials on how to see it.

What do you mean about the changelog?
You mean the Ghost abilities of the mare and the yurei?

If so, I remove it.

When the changes of the footsteps are merged, can I open gold PR with the changes of the Ghost ability?

As soon as you answer me, I make the relevant changes.

Thanks a lot :)

**Comment by Mythra** [comment]
Yep! You got it all right!

**Comment by Misukun** [comment]
Done, Thx :D

**Comment by Mythra** [comment]
Oh! Sorry looks like you missed the demon change as well 😄

**Comment by Misukun** [comment]
Done :D

**Review by Mythra — APPROVED** [review]

**Pull request merged**
